name: flits
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - scipy
  - astropy
  - pandas
  - h5py
  - matplotlib
  - ipython
  - jupyter
  - notebook
  - ipywidgets
  - tqdm
  - pyyaml
  - numba
  - joblib
  - scikit-image
  - uncertainties
  - dynesty
  - pip
  - pip:
    - emcee
    - corner
    - chainconsumer
    - lmfit
    - mwprop
