burst_name: freya
path: ../../../data/chime/freya_chime_I_912_4067_32000b_cntr_bpc.npy
telcfg_path: ../../scattering/configs/telescopes.yaml
sampcfg_path: ../../scattering/configs/sampler.yaml
dm_init: 912.4
telescope: chime
steps: 10000
f_factor: 64
t_factor: 24
nproc: 8
extend_chain: true
chunk_size: 2000
max_chunks: 5
model_scan: true
diagnostics: true
plot: true
