# Casey CHIME Configuration
burst_name: casey
path: data/chime/casey_chime_I_491_2085_32000b_cntr_bpc.npy
telcfg_path: ../../telescopes.yaml
sampcfg_path: ../../sampler.yaml
dm_init: 0.0
telescope: chime
steps: 10000
f_factor: 32
t_factor: 4
likelihood: studentt
alpha_fixed: 4.0
nproc: 16
extend_chain: true
chunk_size: 2000
max_chunks: 5
model_scan: true
diagnostics: true
plot: true
