version: '1.0'
description: FLITS batch processing manifest
data_root: data
bursts:
  zach:
    chime: batch_configs/chime/zach_chime.yaml
    dsa: batch_configs/dsa/zach_dsa.yaml
  hamilton:
    chime: batch_configs/chime/hamilton_chime.yaml
    dsa: batch_configs/dsa/hamilton_dsa.yaml
  wilhelm:
    chime: batch_configs/chime/wilhelm_chime.yaml
    dsa: batch_configs/dsa/wilhelm_dsa.yaml
  chromatica:
    chime: batch_configs/chime/chromatica_chime.yaml
    dsa: batch_configs/dsa/chromatica_dsa.yaml
  mahi:
    chime: batch_configs/chime/mahi_chime.yaml
    dsa: batch_configs/dsa/mahi_dsa.yaml
  phineas:
    chime: batch_configs/chime/phineas_chime.yaml
    dsa: batch_configs/dsa/phineas_dsa.yaml
  johndoeii:
    chime: batch_configs/chime/johndoeii_chime.yaml
    dsa: batch_configs/dsa/johndoeii_dsa.yaml
  whitney:
    chime: batch_configs/chime/whitney_chime.yaml
    dsa: batch_configs/dsa/whitney_dsa.yaml
  isha:
    chime: batch_configs/chime/isha_chime.yaml
    dsa: batch_configs/dsa/isha_dsa.yaml
  freya:
    chime: batch_configs/chime/freya_chime.yaml
    dsa: batch_configs/dsa/freya_dsa.yaml
  casey:
    chime: batch_configs/chime/casey_chime.yaml
    dsa: batch_configs/dsa/casey_dsa.yaml
  oran:
    chime: batch_configs/chime/oran_chime.yaml
    dsa: batch_configs/dsa/oran_dsa.yaml
