burst_name: johndoeii
path: ../../../data/dsa/johndoeII_dsa_I_696_506_2500b_cntr_bpc.npy
telcfg_path: ../../telescopes.yaml
sampcfg_path: ../../sampler.yaml
dm_init: 696.506
telescope: dsa
steps: 10000
f_factor: 384
t_factor: 2
nproc: 8
extend_chain: true
chunk_size: 2000
max_chunks: 5
model_scan: true
diagnostics: true
plot: true
